name: GitLab Mirror

on: [push, create, delete]

permissions:
  contents: read

jobs:
  sync:
    name: Gitlab Mirror
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: action-pack/gitlab-sync@38077a591a7f2ceb6ff6026e6beb2954a3be0f93
        with:
          username: ${{ github.actor }}
          url: https://gitlab.com/${{ github.repository }}.git
          # Personal access token from gitlab.com 
          token: ${{ secrets.GITLAB_TOKEN }}